$(document).ready(function(){

			

			

			$(".blog1").click(function(event){
				  $.post("blog.php",
				 {
					 request:1
				 },
				function(data,status){
				$("#blog-right").html(data);
				});
				event.preventDefault();
			});

			$(".blog2").click(function(event){
				  $.post("blog.php",
				 {
					 request:2
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog3").click(function(event){
				  $.post("blog.php",
				 {
					 request:3
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog4").click(function(event){
				  $.post("blog.php",
				 {
					 request:4
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog5").click(function(event){
				  $.post("blog.php",
				 {
					 request:5
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog6").click(function(event){
				  $.post("blog.php",
				 {
					 request:6
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog7").click(function(event){
				  $.post("blog.php",
				 {
					 request:7
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog8").click(function(event){
				  $.post("blog.php",
				 {
					 request:8
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog9").click(function(event){
				  $.post("blog.php",
				 {
					 request:9
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});
			$(".blog10").click(function(event){
				  $.post("blog.php",
				 {
					 request:10
				 },
				function(data,status){
				$("#blog-right").html(data);
				});event.preventDefault();
			});


			$(".interview1").click(function(event){
				  $.post("interview.php",
				 {
					 request:1
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview2").click(function(event){
				  $.post("interview.php",
				 {
					 request:2
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview3").click(function(event){
				  $.post("interview.php",
				 {
					 request:3
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview4").click(function(event){
				  $.post("interview.php",
				 {
					 request:4
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview5").click(function(event){
				  $.post("interview.php",
				 {
					 request:5
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview6").click(function(event){
				  $.post("interview.php",
				 {
					 request:6
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview7").click(function(event){
				  $.post("interview.php",
				 {
					 request:7
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview8").click(function(event){
				  $.post("interview.php",
				 {
					 request:8
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview9").click(function(event){
				  $.post("interview.php",
				 {
					 request:9
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			$(".interview10").click(function(event){
				  $.post("interview.php",
				 {
					 request:10
				 },
				function(data,status){
				$("#interview-down-right").html(data);
				});event.preventDefault();
			});
			
		});